#!/bin/sh

set -e

update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator \
  /usr/bin/alacritty 20 --slave /usr/share/man/man1/x-terminal-emulator.1.gz \
  x-terminal-emulator.1.gz /usr/share/man/man1/alacritty.1.gz
